name: Alexa Hugenberg
repo_names:
  - Touch-The-Sky
10-ux-ui-criticism:
  - http://
  - http://
11-models-from-data:
  - https://github.com/anhugenberg/Touch-The-Sky/blob/main/TouchSky/TouchSky/TouchSky/Models/ModelData.swift#L10